from tasks.data_aggregation_task import DataAggregationTask
from tasks.data_analyzing_task import DataAnalyzingTask
from tasks.data_calculation_task import DataCalculationTask
from tasks.data_fetching_task import DataFetchingTask
